name: "Prepare Build (OpenAPI generation)"
description: "Sets up Python with uv, installs deps, generates OpenAPI schema and Python client, uploads artifact"
inputs:
  docker-username:
    required: true
  docker-password:
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Python and Install Dependencies
      uses: ./.github/actions/setup-python-and-install-dependencies

    - name: Generate OpenAPI schema
      shell: bash
      working-directory: backend
      env:
        PYTHONPATH: "."
      run: |
        python scripts/onyx_openapi_schema.py --filename generated/openapi.json

    # needed for pulling openapitools/openapi-generator-cli
    # otherwise, we hit the "Unauthenticated users" limit
    # https://docs.docker.com/docker-hub/usage/
    - name: Login to Docker Hub
      uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # ratchet:docker/login-action@v3
      with:
        username: ${{ inputs['docker-username'] }}
        password: ${{ inputs['docker-password'] }}

    - name: Generate OpenAPI Python client
      shell: bash
      run: |
        docker run --rm \
          -v "${{ github.workspace }}/backend/generated:/local" \
          openapitools/openapi-generator-cli generate \
          -i /local/openapi.json \
          -g python \
          -o /local/onyx_openapi_client \
          --package-name onyx_openapi_client \
          --skip-validate-spec \
          --openapi-normalizer "SIMPLIFY_ONEOF_ANYOF=true,SET_OAS3_NULLABLE=true"
