name: "Prepare Build (OpenAPI generation)"
description: "Sets up Python with uv, installs deps, generates OpenAPI schema and Python client, uploads artifact"
inputs:
  docker-username:
    required: true
  docker-password:
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup uv
      uses: astral-sh/setup-uv@caf0cab7a618c569241d31dcd442f54681755d39 # ratchet:astral-sh/setup-uv@v3
      # TODO: Enable caching once there is a uv.lock file checked in.
      # with:
      #   enable-cache: true

    - name: Cache uv cache directory
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # ratchet:actions/cache@v4
      with:
        path: ~/.cache/uv
        key: ${{ runner.os }}-uv-${{ hashFiles('backend/requirements/*.txt', 'backend/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-uv-

    - name: Setup Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # ratchet:actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install Python dependencies with uv
      shell: bash
      run: |
        uv pip install --system \
          -r backend/requirements/default.txt \
          -r backend/requirements/dev.txt \
          -r backend/requirements/model_server.txt

    - name: Generate OpenAPI schema
      shell: bash
      working-directory: backend
      env:
        PYTHONPATH: "."
      run: |
        python scripts/onyx_openapi_schema.py --filename generated/openapi.json

    # needed for pulling openapitools/openapi-generator-cli
    # otherwise, we hit the "Unauthenticated users" limit
    # https://docs.docker.com/docker-hub/usage/
    - name: Login to Docker Hub
      uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # ratchet:docker/login-action@v3
      with:
        username: ${{ inputs['docker-username'] }}
        password: ${{ inputs['docker-password'] }}

    - name: Generate OpenAPI Python client
      shell: bash
      run: |
        docker run --rm \
          -v "${{ github.workspace }}/backend/generated:/local" \
          openapitools/openapi-generator-cli generate \
          -i /local/openapi.json \
          -g python \
          -o /local/onyx_openapi_client \
          --package-name onyx_openapi_client \
          --skip-validate-spec \
          --openapi-normalizer "SIMPLIFY_ONEOF_ANYOF=true,SET_OAS3_NULLABLE=true"

    - name: Upload OpenAPI artifacts
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # ratchet:actions/upload-artifact@v4
      with:
        name: openapi-artifacts
        path: backend/generated/

