name: "Setup Python and Install Dependencies"
description: "Sets up Python with uv and installs deps"
runs:
  using: "composite"
  steps:
    - name: Setup uv
      uses: astral-sh/setup-uv@caf0cab7a618c569241d31dcd442f54681755d39 # ratchet:astral-sh/setup-uv@v3
      # TODO: Enable caching once there is a uv.lock file checked in.
      # with:
      #   enable-cache: true

    - name: Cache uv cache directory
      uses: runs-on/cache@50350ad4242587b6c8c2baa2e740b1bc11285ff4 # ratchet:runs-on/cache@v4
      with:
        path: ~/.cache/uv
        key: ${{ runner.os }}-uv-${{ hashFiles('backend/requirements/*.txt', 'backend/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-uv-

    - name: Setup Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # ratchet:actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Create virtual environment
      shell: bash
      run: |
        uv venv ${{ runner.temp }}/venv
        echo "VENV_PATH=${{ runner.temp }}/venv" >> $GITHUB_ENV
        echo "${{ runner.temp }}/venv/bin" >> $GITHUB_PATH

    - name: Install Python dependencies with uv
      shell: bash
      run: |
        uv pip install \
          -r backend/requirements/default.txt \
          -r backend/requirements/dev.txt \
          -r backend/requirements/model_server.txt
